### ISSUE TITLE
[Feature Request] Ability to add torrents to qBittorrent with a category

### ISSUE THREAD

**Issue by varoOP** [JohnDoee/autotorrent2#33]
It would be great if at2 could add torrents to qBittorrent along with a category. This could be configured under the [clients] header of the configuration file and also be passed as a flag perhaps.

**Comment by JohnDoee** [comment]
The reason it is not there is because it seems like categories have more uses than just a label, i.e. individual save path and torrent management. I'm not sure how commonly used that is though.

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-category

I'm not sure if savePath is required, the qbittorrent API documentation is trash.

**Comment by varoOP** [comment]
Save Path is not required. But yes, you are right. It might be better to just give the option to add a tag which is like a label in Deluge. Adding tags wont require a save path for sure

**Comment by JohnDoee** [comment]
Fixed in 1.2.3
