### ISSUE TITLE
issue connecting to rutorrent

### ISSUE THREAD

**Issue by mpk99** [JohnDoee/autotorrent2#55]
hi there -- used this script before with qbitorrent, but moving to rutorrent.  I'm running this docker container:

https://github.com/crazy-max/docker-rtorrent-rutorrent

but i can't figure out how to connect to it: i tried what was suggested here:

https://github.com/JohnDoee/autotorrent2/issues/29#issuecomment-1214219069

but it just gives me a 401 error when trying to runt the test connection command.

Hopefully somebody can help?

thx

**Comment by JohnDoee** [comment]
It can't connect to rutorrent, only rtorrent directly.

**Comment by mpk99** [comment]
k. well I guess how can I get it to point to my torrent instance? I can't figure out where to find the proper values?

**Comment by JohnDoee** [comment]
With that rtorrent setup it is probably not that easy. The container you're looking at is designed to not expose rtorrent directly (because it can be insecure).

The setting you need into .rtorrent.rc is found here: https://github.com/rakshasa/rtorrent/blob/1da0e3476dcabbf74b2e836d6b4c37b4d96bde09/doc/rtorrent.rc#L126
It has to listen to something like 0.0.0.0 and NOT be exposed directly to the internet.

e.g. `network.scgi.open_port = "0.0.0.0:5000"` then autotorrent can reach rtorrent on port 5000.

**Comment by GregTroar** [comment]
any way to connect through socket rather than scgi port ?
